//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Processes = new HashSet<Process>();
            this.Histories = new HashSet<History>();
            this.Programs = new HashSet<Program>();
        }
    
        public int Id { get; set; }
        public string Domain { get; set; }
        public string UserName { get; set; }
        public byte[] Tracking { get; set; }
        public int AllottedTime { get; set; }
        public int UsedTime { get; set; }
        public int ComputerId { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
    }
}
