//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.Histories = new HashSet<History>();
            this.Processes = new HashSet<Processes>();
            this.Programs = new HashSet<Programs>();
        }
    
        public int Id { get; set; }
        public string Domain { get; set; }
        public string Username { get; set; }
        public System.DateTime DateLastLogin { get; set; }
        public System.TimeSpan AllottedTime { get; set; }
        public System.TimeSpan UsedTime { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Processes> Processes { get; set; }
        public virtual ICollection<Programs> Programs { get; set; }
    }
}
