//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int Id { get; set; }
        public int AccountsId { get; set; }
        public string Name { get; set; }
        public System.TimeSpan TotalRunTime { get; set; }
        public System.DateTime LastOpened { get; set; }
        public int OpenCount { get; set; }
    
        public virtual Accounts Account { get; set; }
    }
}
